[pytest]
addopts = --import-mode=importlib
testpaths =
    literegistry_tool_client/tests
    tests
    literegistry_podman_client/tests
    literegistry_podman_beaker/tests
    literegistry_base_deployment/tests
pythonpath =
    literegistry_tool_client/src
    literegistry_podman_client/src
    literegistry_podman_beaker/src
    literegistry_base_deployment/src
